#!/usr/bin/env python3
"""Dimension-four rational Gram search for the order-five rank-five frontier.

The input is regenerated by order5-tetra-census-experiment.py.  Continuous
Riemannian optimization only proposes vectors.  Every accepted result is
reconstructed from rational stereographic vectors and checked with Fraction.
This is an experiment and does not modify a main verifier or theorem fixture.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import itertools
import json
import math
import random
from fractions import Fraction
from pathlib import Path


HERE = Path(__file__).resolve().parent
CENSUS_SCRIPT = HERE / "order5-tetra-census-experiment.py"
OUTPUT = HERE / "order5-dim4-rational-gram-results.json"
PAIRS = tuple(itertools.combinations(range(5), 2))
BUDGET = Fraction(4)
DIMENSION = 4


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def dot(left, right):
    return sum(x * y for x, y in zip(left, right))


def normalized(vector):
    norm = math.sqrt(dot(vector, vector))
    require(norm > 1e-14, "cannot normalize a zero vector")
    return tuple(x / norm for x in vector)


def path_cost_and_derivative(correlation, length):
    sign = -1.0 if length & 1 else 1.0
    transformed = max(-1.0 + 1e-14, min(1.0 - 1e-14,
                                        sign * correlation))
    angle = math.acos(transformed)
    tangent = math.tan(angle / (2.0 * length))
    cost = length * tangent * tangent
    derivative = (-sign * tangent * (1.0 + tangent * tangent)
                  / math.sqrt(max(1e-28, 1.0 - transformed * transformed)))
    return cost, derivative


def objective_and_gradient(paths, vectors):
    total = 0.0
    gradient = [[0.0] * DIMENSION for _ in range(5)]
    for _, _, u, v, length in paths:
        cost, derivative = path_cost_and_derivative(dot(vectors[u], vectors[v]),
                                                    length)
        total += cost
        for coordinate in range(DIMENSION):
            gradient[u][coordinate] += derivative * vectors[v][coordinate]
            gradient[v][coordinate] += derivative * vectors[u][coordinate]
    for vertex in range(1, 5):
        radial = dot(gradient[vertex], vectors[vertex])
        gradient[vertex] = [value - radial * coordinate
                            for value, coordinate in zip(gradient[vertex],
                                                         vectors[vertex])]
    gradient[0] = [0.0] * DIMENSION
    return total, gradient


def objective(paths, vectors):
    return objective_and_gradient(paths, vectors)[0]


def random_vectors(generator):
    return ((1.0, 0.0, 0.0, 0.0),) + tuple(
        normalized(tuple(generator.gauss(0.0, 1.0) for _ in range(DIMENSION)))
        for _ in range(4))


def descend(paths, initial, iterations):
    vectors = tuple(initial)
    value = objective(paths, vectors)
    step = 0.25
    stagnant = 0
    for _ in range(iterations):
        value, gradient = objective_and_gradient(paths, vectors)
        norm = math.sqrt(sum(dot(row, row) for row in gradient))
        if norm < 1e-10:
            break
        accepted = False
        trial_step = step
        for _ in range(18):
            candidate = [vectors[0]]
            for vertex in range(1, 5):
                candidate.append(normalized(tuple(
                    vectors[vertex][coordinate]
                    - trial_step * gradient[vertex][coordinate]
                    for coordinate in range(DIMENSION))))
            candidate = tuple(candidate)
            candidate_value = objective(paths, candidate)
            if candidate_value < value - 1e-5 * trial_step * norm * norm:
                vectors, value = candidate, candidate_value
                step = min(0.8, trial_step * 1.35)
                accepted = True
                stagnant = 0
                break
            trial_step *= 0.5
        if not accepted:
            step *= 0.25
            stagnant += 1
            if step < 1e-11 or stagnant == 8:
                break
    return value, vectors


def optimize(paths, seed, restarts, iterations, warm=()):
    generator = random.Random(seed)
    starts = list(warm)
    starts.extend(random_vectors(generator) for _ in range(restarts))
    best = (float("inf"), None)
    for initial in starts:
        candidate = descend(paths, initial, iterations)
        if candidate[0] < best[0]:
            best = candidate
    return best


def canonical_lengths(multiplicity, odd):
    require(0 <= odd <= multiplicity, "invalid physical odd count")
    return (([1] + [3] * (odd - 1)) if odd else []) + [2] * (multiplicity - odd)


def path_ledger(kernel, row, frontier=None):
    paths = []
    for edge, ((u, v), multiplicity, odd) in enumerate(zip(PAIRS, kernel, row)):
        paths.extend((edge, occurrence, u, v, length)
                     for occurrence, length in enumerate(
                         canonical_lengths(multiplicity, odd)))
    require(len(paths) == 9, "order-five rank-five path count changed")
    if frontier is not None:
        edge, occurrence, u, v, length = paths[frontier]
        paths[frontier] = edge, occurrence, u, v, length + 2
    return tuple(paths)


def rotate_away_from_pole(vectors):
    choices = []
    for coordinate in range(DIMENSION):
        for sign in (-1.0, 1.0):
            margin = min(1.0 + sign * vector[coordinate] for vector in vectors)
            choices.append((margin, coordinate, sign))
    _, first, sign = max(choices)
    order = (first,) + tuple(i for i in range(DIMENSION) if i != first)
    return tuple(tuple((sign if position == 0 else 1.0) * vector[coordinate]
                       for position, coordinate in enumerate(order))
                 for vector in vectors)


def snap_coincident_vectors(vectors):
    result = list(vectors)
    for vertex in range(1, len(result)):
        for earlier in range(vertex):
            correlation = dot(result[vertex], result[earlier])
            if correlation > 1.0 - 1e-9:
                result[vertex] = result[earlier]
                break
            if correlation < -1.0 + 1e-9:
                result[vertex] = tuple(-value for value in result[earlier])
                break
    return tuple(result)


def stereographic(vector, denominator):
    scale = 1.0 + vector[0]
    require(abs(scale) > 1e-10, "stereographic pole encountered")
    return tuple(Fraction(round(coordinate / scale * denominator), denominator)
                 for coordinate in vector[1:])


def rational_unit(parameters):
    square = sum(value * value for value in parameters)
    denominator = 1 + square
    return ((1 - square) / denominator,) + tuple(
        2 * value / denominator for value in parameters)


def slerp(left, right, fraction):
    correlation = max(-1.0, min(1.0, dot(left, right)))
    angle = math.acos(correlation)
    if angle < 1e-12:
        return left
    sine = math.sin(angle)
    return normalized(tuple(
        (math.sin((1.0 - fraction) * angle) * x
         + math.sin(fraction * angle) * y) / sine
        for x, y in zip(left, right)))


def exact_step_cost(left, right):
    correlation = dot(left, right)
    require(correlation != -1, "antipodal rational step")
    return (1 - correlation) / (1 + correlation)


def rationalize(paths, vectors, denominators):
    vectors = rotate_away_from_pole(snap_coincident_vectors(vectors))
    for denominator in denominators:
        branch_parameters = tuple(stereographic(vector, denominator)
                                  for vector in vectors)
        branches = tuple(rational_unit(row) for row in branch_parameters)
        total = Fraction(0)
        internal_parameters = []
        try:
            for _, _, u, v, length in paths:
                endpoint = vectors[v] if length % 2 == 0 else tuple(
                    -value for value in vectors[v])
                numerical = tuple(slerp(vectors[u], endpoint, j / length)
                                  for j in range(1, length))
                parameters = tuple(stereographic(vector, denominator)
                                   for vector in numerical)
                internal_parameters.append(parameters)
                exact = [branches[u], *(rational_unit(row) for row in parameters)]
                exact.append(branches[v] if length % 2 == 0 else tuple(
                    -value for value in branches[v]))
                total += sum(exact_step_cost(left, right)
                             for left, right in zip(exact, exact[1:]))
        except (RuntimeError, ZeroDivisionError):
            continue
        if total <= BUDGET:
            witness = {
                "denominator": denominator,
                "cost": [total.numerator, total.denominator],
                "branches": [[[value.numerator, value.denominator] for value in row]
                             for row in branch_parameters],
                "internals": [[[[value.numerator, value.denominator] for value in row]
                               for row in path] for path in internal_parameters],
            }
            return total, witness
    return None, None


def target_archetype(paths):
    bundles = {pair: [] for pair in PAIRS}
    for _, _, u, v, length in paths:
        bundles[(u, v)].append(length)
    encodings = []
    for permutation in itertools.permutations(range(5)):
        transformed = {}
        for pair, lengths in bundles.items():
            image = tuple(sorted((permutation[pair[0]], permutation[pair[1]])))
            transformed[image] = tuple(sorted(lengths))
        encodings.append(tuple(transformed[pair] for pair in PAIRS))
    return min(encodings)


def encode_archetype(archetype):
    return [list(lengths) for lengths in archetype]


def load_census():
    spec = importlib.util.spec_from_file_location("order5_census", CENSUS_SCRIPT)
    require(spec is not None and spec.loader is not None, "cannot load census")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.audit()


def canonical_json(payload):
    return json.dumps(payload, sort_keys=True, separators=(",", ":")) + "\n"


def run(args):
    census = load_census()
    kernels = {record["kernel"]: tuple(record["code"])
               for record in census["kernels"]}
    targets = [(number, tuple(row))
               for number, row in census["search_target_keys"]]
    records = []
    archetypes = {}
    true_archetypes = set()
    obstruction_archetypes = set()
    denominators = tuple(int(value) for value in args.denominators.split(","))
    for target_index, (number, row) in enumerate(targets):
        kernel = kernels[number]
        canonical_paths = path_ledger(kernel, row)
        canonical_value, canonical_vectors = optimize(
            canonical_paths, args.seed + 1009 * target_index, args.restarts,
            args.iterations)
        for frontier in (None, *range(9)):
            paths = canonical_paths if frontier is None else path_ledger(
                kernel, row, frontier)
            if frontier is None:
                value, vectors = canonical_value, canonical_vectors
            else:
                value, vectors = optimize(
                    paths, args.seed + 1009 * target_index + frontier + 1,
                    args.frontier_restarts, args.iterations,
                    warm=(canonical_vectors,))
            exact, witness = rationalize(paths, vectors, denominators)
            archetype = target_archetype(paths)
            archetype_key = repr(archetype)
            archetypes.setdefault(archetype_key, encode_archetype(archetype))
            if exact is None:
                obstruction_archetypes.add(archetype_key)
            else:
                true_archetypes.add(archetype_key)
            records.append({
                "kernel": number,
                "row": list(row),
                "frontier": frontier,
                "lengths": [path[4] for path in paths],
                "numerical_cost": float(f"{value:.12g}"),
                "exact_dnn_le_4": exact is not None,
                "archetype": archetype_key,
                "witness": witness,
            })
        if args.progress:
            certified = sum(record["exact_dnn_le_4"] for record in records)
            print(f"[{target_index + 1}/{len(targets)}] K{number} "
                  f"certified={certified}/{len(records)}", flush=True)
    payload = {
        "schema": "rank-five-order-five-dim4-rational-gram-search-v1",
        "status": "experimental_exact_positive_certificates",
        "dimension": DIMENSION,
        "budget": [4, 1],
        "algorithm": "Riemannian nonconvex optimization then rational stereographic verification",
        "source_census_sha256": hashlib.sha256(canonical_json(census).encode("ascii")).hexdigest(),
        "canonical_target_total": len(targets),
        "frontiers_per_target": 10,
        "target_total": len(records),
        "exact_dnn_le_4_total": sum(record["exact_dnn_le_4"] for record in records),
        "optimized_obstruction_total": sum(not record["exact_dnn_le_4"] for record in records),
        "archetype_total": len(archetypes),
        "exact_dnn_le_4_archetype_total": len(true_archetypes),
        "optimized_obstruction_archetype_total": len(obstruction_archetypes),
        "archetypes": archetypes,
        "records": records,
    }
    return payload


def report(payload):
    obstruction_records = [record for record in payload["records"]
                           if not record["exact_dnn_le_4"]]
    print("order-five dimension-four rational Gram search complete")
    print(f"targets={payload['target_total']} exact_dnn_le_4="
          f"{payload['exact_dnn_le_4_total']} optimized_obstructions="
          f"{payload['optimized_obstruction_total']}")
    print(f"archetypes={payload['archetype_total']} exact_dnn_le_4_archetypes="
          f"{payload['exact_dnn_le_4_archetype_total']} obstruction_archetypes="
          f"{payload['optimized_obstruction_archetype_total']}")
    for record in sorted(obstruction_records,
                         key=lambda row: row["numerical_cost"], reverse=True):
        print(f"obstruction K{record['kernel']} row={tuple(record['row'])} "
              f"frontier={record['frontier']} numerical={record['numerical_cost']:.12g} "
              f"lengths={tuple(record['lengths'])}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", type=int, default=173)
    parser.add_argument("--restarts", type=int, default=10)
    parser.add_argument("--frontier-restarts", type=int, default=2)
    parser.add_argument("--iterations", type=int, default=1200)
    parser.add_argument("--denominators", default="256,1024,4096,16384,65536")
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--progress", action="store_true")
    args = parser.parse_args()
    payload = run(args)
    require(args.output.parent.is_dir(), "output parent does not exist")
    args.output.write_text(canonical_json(payload), encoding="ascii")
    report(payload)


if __name__ == "__main__":
    main()
