\\ Cycle 211: exact p=7 one-prime Kurihara certificate for D=-29023.
E = ellinit([1,0,0,0,1]);
A = ellinit([1,1,1,-17548636,-24475377572834]);
[M, xm] = msfromell(E, -1);

p = 7;
q = 29023;
ell = 113;
generator = 3;
expected = -17186;

change = 0;
Acheck = ellminimalmodel(elltwist(E, -q), &change);
if (change[1] != 1 || [Acheck.a1,Acheck.a2,Acheck.a3,Acheck.a4,Acheck.a6] != [1,1,1,-17548636,-24475377572834], error("minimal twist or differential comparison mismatch"));
if (!isprime(ell), error("113 is not prime"));
if (znorder(Mod(generator, ell)) != ell-1, error("3 is not primitive modulo 113"));
if (ell % p != 1 || (ellap(A, ell) - ell - 1) % p != 0, error("113 is not a Kolyvagin prime at p=7"));
forprime (r = 2, ell-1, if (r != 29 && r % p == 1 && (ellap(A, r) - r - 1) % p == 0, error("unexpected intervening Kolyvagin prime: ", r)));

modp(x) =
{
  my(d = denominator(x));
  if (d % p == 0, error("nonintegral completed twist symbol at 7: ", x));
  lift(Mod(numerator(x), p) / Mod(d, p));
};

twist_symbol(a) =
{
  my(U = 0);
  for (u = 1, q-1,
    U += kronecker(u, q) * mseval(M, xm, [oo, (a*q + ell*u)/(ell*q)]));
  modp(U);
  U;
};

C = 0;
for (a = 1, ell-1, C += lift(znlog(Mod(a, ell), Mod(generator, ell))) * twist_symbol(a));

if (C != expected, error("exact Kurihara lift mismatch: ", C));
if (modp(C) != 6, error("Kurihara residue mismatch: ", modp(C)));

Al = ellinit([Mod(1,ell),Mod(1,ell),Mod(1,ell),Mod(-17548636,ell),Mod(-24475377572834,ell)]);
G = [Mod(85,ell), Mod(7,ell)];
W = ellmul(Al, G, 16);
if (ellcard(Al) != 112 || ellorder(Al, G) != 112, error("finite group witness mismatch"));
if (lift(W) != [53,42] || ellorder(Al, W) != 7, error("local quotient generator mismatch"));

print("PASS Cycle 211 D=-29023 p=7 Kurihara certificate");
print("ell=113 eta=3 #A(F_113)=112 a_113=2");
print("delta_tilde_113=", C, " = ", modp(C), " mod 7");
print("G=(85,7) has order 112; 16G=(53,42) has order 7");
print("A(F_113)/7A(F_113) is generated by the class of G");
