#!/usr/bin/env python3
"""Dependency-free hostile audit of the proposed Cycle 184 q-pair."""

import sys


ELL = 7
P = (0, 1)
Q = (-1, 1)
INFINITY = None
CYCLOTOMIC_MODULUS = 8 * 7 * 433 * 29
CASES = (
    (17599, 17731, ((7, 1), (17, 1), (149, 1)), (1566, 13374), 8498),
    (30367, 30289, ((7, 1), (4327, 1)), (8547, 22669), 22323),
)


class VerificationError(Exception):
    pass


def check(condition, message):
    if not condition:
        raise VerificationError(message)


def is_prime(number):
    if number < 2:
        return False
    if number % 2 == 0:
        return number == 2
    divisor = 3
    while divisor * divisor <= number:
        if number % divisor == 0:
            return False
        divisor += 2
    return True


def factor(number):
    factors = []
    divisor = 2
    while divisor * divisor <= number:
        exponent = 0
        while number % divisor == 0:
            number //= divisor
            exponent += 1
        if exponent:
            factors.append((divisor, exponent))
        divisor = 3 if divisor == 2 else divisor + 2
    if number > 1:
        factors.append((number, 1))
    return tuple(factors)


def normalize(point, prime):
    if point is INFINITY:
        return INFINITY
    return point[0] % prime, point[1] % prime


def on_curve(point, prime):
    if point is INFINITY:
        return True
    x, y = normalize(point, prime)
    return (y * y + x * y - x * x * x - 1) % prime == 0


def point_neg(point, prime):
    if point is INFINITY:
        return INFINITY
    x, y = normalize(point, prime)
    return x, (-y - x) % prime


def point_add(left, right, prime):
    left = normalize(left, prime)
    right = normalize(right, prime)
    if left is INFINITY:
        return right
    if right is INFINITY:
        return left
    if right == point_neg(left, prime):
        return INFINITY

    x1, y1 = left
    x2, y2 = right
    if x1 != x2:
        inverse = pow((x2 - x1) % prime, -1, prime)
        slope = (y2 - y1) * inverse % prime
        intercept = (y1 * x2 - y2 * x1) * inverse % prime
    else:
        denominator = (2 * y1 + x1) % prime
        check(denominator != 0, "unexpected vertical tangent")
        inverse = pow(denominator, -1, prime)
        slope = (3 * x1 * x1 - y1) * inverse % prime
        intercept = (-x1 * x1 * x1 + 2) * inverse % prime

    x3 = (slope * slope + slope - x1 - x2) % prime
    result = x3, (-(slope + 1) * x3 - intercept) % prime
    check(on_curve(result, prime), "addition produced an off-curve point")
    return result


def scalar_multiply(multiplier, point, prime):
    if multiplier < 0:
        return scalar_multiply(-multiplier, point_neg(point, prime), prime)
    result = INFINITY
    addend = normalize(point, prime)
    while multiplier:
        if multiplier & 1:
            result = point_add(result, addend, prime)
        addend = point_add(addend, addend, prime)
        multiplier //= 2
    return result


def group_order(prime):
    total = 1
    for x in range(prime):
        discriminant = (x * x + 4 * (x * x * x + 1)) % prime
        if discriminant == 0:
            total += 1
        elif pow(discriminant, (prime - 1) // 2, prime) == 1:
            total += 2
    return total


def point_order(point, prime, order, factors):
    result = order
    for divisor, exponent in factors:
        for _ in range(exponent):
            if scalar_multiply(result // divisor, point, prime) is INFINITY:
                result //= divisor
            else:
                break
    return result


def discrete_log(base, target, prime, bound):
    current = INFINITY
    target = normalize(target, prime)
    for coefficient in range(bound):
        if current == target:
            return coefficient
        current = point_add(current, base, prime)
    raise VerificationError(f"target is not generated by base in E(F_{prime})")


def verify_case(case):
    prime, expected_order, expected_factors, witness, expected_log = case
    check(is_prime(prime), f"{prime} is not prime")
    check(prime not in (7, 433), f"{prime} is not a good auxiliary prime")
    check(on_curve(P, prime) and on_curve(Q, prime), "P or Q is off curve")

    order = group_order(prime)
    factors = factor(order)
    check(order == expected_order, f"#E(F_{prime})={order}, expected {expected_order}")
    check(factors == expected_factors, f"factorization mismatch at {prime}: {factors}")
    check(order % ELL == 0 and order % (ELL * ELL) != 0,
          f"v_7(#E(F_{prime})) is not one")

    order_p = point_order(P, prime, order, factors)
    order_q = point_order(Q, prime, order, factors)
    check(order_p == order, f"P has order {order_p}, not {order}")
    check(order_q == order // ELL,
          f"Q has order {order_q}, not {order // ELL}")

    cofactor = order // ELL
    check(scalar_multiply(cofactor, P, prime) is not INFINITY,
          f"P is zero in E(F_{prime})/7E(F_{prime})")
    check(scalar_multiply(cofactor, Q, prime) is INFINITY,
          f"Q is nonzero in E(F_{prime})/7E(F_{prime})")
    check(on_curve(witness, prime), f"stored witness at {prime} is off curve")
    check(scalar_multiply(ELL, witness, prime) == normalize(Q, prime),
          f"7*witness != Q at {prime}")

    log_q = discrete_log(P, Q, prime, order)
    check(log_q == expected_log, f"Q log_P is {log_q}, expected {expected_log}")
    check(log_q % ELL == 0, f"Q log_P is not divisible by seven at {prime}")
    return {
        "prime": prime,
        "order": order,
        "factors": factors,
        "trace": prime + 1 - order,
        "order_p": order_p,
        "order_q": order_q,
        "row": (1, 0),
        "witness": witness,
        "log_q": log_q,
    }


def main():
    try:
        results = tuple(verify_case(case) for case in CASES)
        first, second = (result["prime"] for result in results)
        check(first % CYCLOTOMIC_MODULUS != second % CYCLOTOMIC_MODULUS,
              "the two primes unexpectedly have equal cyclotomic Frobenius")
    except (ArithmeticError, VerificationError, ValueError) as error:
        print(f"FAIL: {error}", file=sys.stderr)
        return 1

    print("PASS hostile Cycle 184 q-pair arithmetic audit")
    for result in results:
        print(
            f"q={result['prime']}: #E(F_q)={result['order']}="
            + "*".join(
                str(prime) if exponent == 1 else f"{prime}^{exponent}"
                for prime, exponent in result["factors"]
            )
            + f", a_q={result['trace']}"
        )
        print(
            f"  ord(P)={result['order_p']}, ord(Q)={result['order_q']}, "
            f"Q={result['log_q']}P, row={result['row']} mod 7"
        )
        print(f"  divisibility witness: Q=7*{result['witness']}")
    print(f"cyclotomic modulus M=8*7*433*29={CYCLOTOMIC_MODULUS}")
    print(
        "cyclotomic residues: "
        + ", ".join(f"{q}->{q % CYCLOTOMIC_MODULUS}" for q in (first, second))
    )
    print(
        "component residues (mod 8,7,433,29): "
        + "; ".join(
            f"{q}->{tuple(q % modulus for modulus in (8, 7, 433, 29))}"
            for q in (first, second)
        )
    )
    print("verdict: row claim passes; cyclotomic Frobenius match fails")
    return 0


if __name__ == "__main__":
    sys.exit(main())
